project_name: xxx

env: 测试环境
tester_name: swb

# 域名1
host: https://www.wanandroid.com
# 域名2，支持多个域名配置
app_host:
# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: True

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False


#sawwger文件地址
swagger_json_path: ./file/test_OpenAPI.json

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=69d14c6246213110427b0726bf56670abb98dca39a5c04d7f52055c4d68ca850
  secret: SEC4d4f05778aba076fff467f9c387596525f32c4b84829925be2e7220439cf98cf
# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: True
  host: 127.0.0.1
  user: root
  password: 'Swb123520.'
  port: 3306

#Redis相关配置
redis:
    host : '127.0.0.1'
    port : 6379
    database : 0
    password : 123456
    charset : 'UTF-8'
# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
email:
  send_user:
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key:
  # 收件人改成自己的邮箱
  send_list:

# 飞书通知
lark:
  webhook:



